INFO 2021-06-04 15:14:42,327 remote_connection.py:117 __init__ Could not connect to port 4723 on host localhost
INFO 2021-06-04 15:14:42,327 remote_connection.py:136 __init__ Could not get IP address for host: localhost
DEBUG 2021-06-04 15:14:42,328 remote_connection.py:388 _request POST http://localhost:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:platformVersion": "10", "appium:deviceName": "89LJQWROR47TCYKJ", "appium:appPackage": "com.ss.android.ugc.aweme.lite", "appium:appActivity": "com.ss.android.ugc.aweme.splash.SplashActivity", "appium:unicodeKeyboard": false, "appium:resetKeyboard": false, "appium:noReset": true, "appium:newCommandTimeout": 6000, "appium:automationName": "UiAutomator2"}]}, "desiredCapabilities": {"platformName": "Android", "platformVersion": "10", "deviceName": "89LJQWROR47TCYKJ", "appPackage": "com.ss.android.ugc.aweme.lite", "appActivity": "com.ss.android.ugc.aweme.splash.SplashActivity", "unicodeKeyboard": false, "resetKeyboard": false, "noReset": true, "newCommandTimeout": 6000, "automationName": "UiAutomator2"}}
DEBUG 2021-06-04 15:14:42,331 connectionpool.py:231 _new_conn Starting new HTTP connection (1): localhost:4723
DEBUG 2021-06-04 15:14:46,381 retry.py:576 increment Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING 2021-06-04 15:14:46,381 connectionpool.py:781 urlopen Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001637CC92C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG 2021-06-04 15:14:46,382 connectionpool.py:231 _new_conn Starting new HTTP connection (2): localhost:4723
DEBUG 2021-06-04 15:14:50,422 retry.py:576 increment Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING 2021-06-04 15:14:50,422 connectionpool.py:781 urlopen Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001637CCB1508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG 2021-06-04 15:14:50,423 connectionpool.py:231 _new_conn Starting new HTTP connection (3): localhost:4723
DEBUG 2021-06-04 15:14:54,465 retry.py:576 increment Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING 2021-06-04 15:14:54,466 connectionpool.py:781 urlopen Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001637CCB1E48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
DEBUG 2021-06-04 15:14:54,466 connectionpool.py:231 _new_conn Starting new HTTP connection (4): localhost:4723
